[project]
name = "engine-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.2.1",
    "eval7>=0.1.10",
    "pkrbot>=1.0.1",
    "setuptools>=80.9.0",
]
